docs_dir: ./docs
site_name: Firelink Documentation

markdown_extensions: 
  - toc:
      permalink: "#"

nav:
- Home: index.md
- Known Issues: known_issues.md
- Namespaces: namespaces.md
- Apps: apps.md
- Cluster: cluster.md
- User Menu: user_menu.md
