apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: firelink-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: FrontendEnvironment
    metadata:
      name: firelink
    spec:
      generateNavJSON: false
      ssl: true
      hostname: 'firelink.apps.crc-eph.r9lp.p1.openshiftapps.com'
      sso: 'https://sso.stage.redhat.com/auth/'
      enableAkamaiCacheBust: false
      ingressClass: openshift-default