apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: insights-chrome
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: firelink-frontend
    spec:
      envName: '${ENV_NAME}'
      API:
        versions:
          - v1
      frontend:
        paths:
          - /
      deploymentRepo: 'https://github.com/RedHatInsights/firelink-frontend'
      image: '${IMAGE}:${IMAGE_TAG}'
      module:
        config:
          ssoUrl: 'https://'
        manifestLocation: /apps/chrome/js/fed-mods.json
      title: Firelink Frontend
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: firelink-route
    spec:
      to:
        kind: Service
        name: firelink-frontend
      port:
        targetPort: 8000
      wildcardPolicy: None
parameters:
  - name: ENV_NAME
    description: Frontend Environment Name
    required: true
  - name: IMAGE
    description: Frontend Image
    required: true
  - name: IMAGE_TAG
    description: Frontend Image Tag
    required: true
